version: "3.7"
services:
  server:
    container_name: notangles-server
    image: notangles-server
    restart: always
    build: .
    depends_on: 
      - database
    ports:
      - "3001:3001"
    links:
      - database
  database:
    container_name: notangles-database
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - ~/var/lib/notangles/data:/data/db
    